### ISSUE TITLE
arm processor: shared library problem

### ISSUE THREAD

**Issue by yassin-git** [ezflash/ezFlashCLI#24]
Hello ,
I encountered this problem while trying to run ezFlashCLI list cmd:

INFO:root:By using the program you accept the SEGGER J-link™ license
ERROR:root:Error loading J-Link Library: /home/rock/.local/lib/python3.8/site-packages/ezFlashCLI/ezFlash/../third-party/segger/libjlinkarm.so.6.82.2: cannot open shared object file: No such file or directory
Exception ignored in: <function pyjlink.__del__ at 0x7f9c9af040>
Traceback (most recent call last):
  File "/home/rock/.local/lib/python3.8/site-packages/ezFlashCLI/ezFlash/pyjlink.py", line 192, in __del__
    self.close()
  File "/home/rock/.local/lib/python3.8/site-packages/ezFlashCLI/ezFlash/pyjlink.py", line 328, in close
    self.jl.JLINKARM_Close()
AttributeError: 'NoneType' object has no attribute 'JLINKARM_Close'

Any ideas ?
Thanks

**Comment by yassin-git** [comment]
This my processor spec:
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  3
Socket(s):           2
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1800,0000
CPU min MHz:         408,0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

**Comment by ezflash** [comment]
This is weird, it looks like the install is not complete. 

can you try to run :

```console
pip install --upgrade --force-reinstall ezFlashCLI
```

that should force the library to be reinstall and all the files to be there.

If that still does not do the job, can you please check what it the content of the _/home/rock/.local/lib/python3.8/site-packages/ezFlashCLI/ezFlash/../third-party/segger_ folder.

It should look like this folder: https://github.com/ezflash/ezFlashCLI/tree/main/ezFlashCLI/third-party/segger

**Comment by yassin-git** [comment]
Hello,
In fact the error still persists despite  the availabilty of  all the files in  /home/rock/.local/lib/python3.8/site-packages/ezFlashCLI/ezFlash/../third-party/segger folder .

**Comment by yassin-git** [comment]
Hello,
So the problem was with segger jlink package. We must install the last version to ARM processor from official website (https://www.segger.com/downloads/jlink ) and move ".so" libraries to ezFlash "" https://github.com/ezflash/ezFlashCLI/tree/main/ezFlashCLI/third-party/segger "" directory and then change pylink.py file with the appropriate version of ".so" library .

**Comment by ezflash** [comment]
You shouldn't have to do that. I suppose the root cause of the issue is permission. But as I cannot reproduce, I can't be sure. Thanks for the feedback.
